// GENERATED by scripts/gen-agent-discovery.py — do not edit.
// Public path -> its markdown rendering, for Accept: text/markdown.
export const MD_MAP = {
  '/': { asset: '/index.md', tokens: 3087 },
  '/index.md': { asset: '/index.md', tokens: 3087 },
  '/blog': { asset: '/blog.md', tokens: 33127 },
  '/blog.md': { asset: '/blog.md', tokens: 33127 },
  '/lineage': { asset: '/lineage.md', tokens: 1994 },
  '/lineage.md': { asset: '/lineage.md', tokens: 1994 },
  '/roadmap': { asset: '/roadmap.md', tokens: 2104 },
  '/roadmap.md': { asset: '/roadmap.md', tokens: 2104 },
  '/supporters': { asset: '/supporters.md', tokens: 495 },
  '/supporters.md': { asset: '/supporters.md', tokens: 495 },
};
