// GENERATED by scripts/gen-agent-discovery.py — do not edit.
// Public path -> its markdown rendering, for Accept: text/markdown.
export const MD_MAP = {
  '/': { asset: '/index.md', tokens: 3087 },
  '/index.md': { asset: '/index.md', tokens: 3087 },
  '/blog': { asset: '/blog.md', tokens: 24981 },
  '/blog.md': { asset: '/blog.md', tokens: 24981 },
  '/lineage': { asset: '/lineage.md', tokens: 1994 },
  '/lineage.md': { asset: '/lineage.md', tokens: 1994 },
  '/supporters': { asset: '/supporters.md', tokens: 468 },
  '/supporters.md': { asset: '/supporters.md', tokens: 468 },
};
