// GENERATED by scripts/gen-agent-discovery.py — do not edit.
// Public path -> its markdown rendering, for Accept: text/markdown.
export const MD_MAP = {
  '/': { asset: '/index.md', tokens: 3147 },
  '/index.md': { asset: '/index.md', tokens: 3147 },
  '/blog': { asset: '/blog.md', tokens: 42082 },
  '/blog.md': { asset: '/blog.md', tokens: 42082 },
  '/lineage': { asset: '/lineage.md', tokens: 1994 },
  '/lineage.md': { asset: '/lineage.md', tokens: 1994 },
  '/roadmap': { asset: '/roadmap.md', tokens: 3811 },
  '/roadmap.md': { asset: '/roadmap.md', tokens: 3811 },
};
