// GENERATED by scripts/gen-agent-discovery.py from _headers — do not edit.
// Pages does not apply _headers to Function responses; the middleware
// replays these onto anything it returns so the two never disagree.
export const HEADER_RULES = [
  ["/*", {"X-Content-Type-Options": "nosniff", "X-Frame-Options": "DENY", "Referrer-Policy": "strict-origin-when-cross-origin", "Permissions-Policy": "geolocation=(), microphone=(), camera=(), interest-cohort=()", "Content-Security-Policy": "default-src 'self'; img-src 'self' data:; style-src 'self' 'unsafe-inline'; script-src 'self'; connect-src 'self' https://api.github.com; font-src 'self' data:; base-uri 'self'; form-action 'self'; frame-ancestors 'none'; upgrade-insecure-requests", "Link": "</.well-known/api-catalog>; rel=\"api-catalog\"; type=\"application/linkset+json\", </api/v1/openapi.json>; rel=\"service-desc\"; type=\"application/vnd.oai.openapi+json\", </api/v1/docs.md>; rel=\"service-doc\"; type=\"text/markdown\", </.well-known/agent-skills/index.json>; rel=\"describedby\"; type=\"application/json\", </sitemap.xml>; rel=\"sitemap\"; type=\"application/xml\", <https://www.gnu.org/licenses/gpl-3.0.html>; rel=\"license\", <https://github.com/aethersdr/AetherSDR>; rel=\"related\""}],
  ["/assets/*", {"Cache-Control": "public, max-age=31536000, immutable"}],
  ["/.well-known/api-catalog", {"Content-Type": "application/linkset+json", "Cache-Control": "public, max-age=3600", "Access-Control-Allow-Origin": "*"}],
  ["/.well-known/agent-skills/index.json", {"Content-Type": "application/json; charset=utf-8", "Cache-Control": "public, max-age=3600", "Access-Control-Allow-Origin": "*"}],
  ["/.well-known/agent-skills/*", {"Content-Type": "text/markdown; charset=utf-8", "Cache-Control": "public, max-age=3600", "Access-Control-Allow-Origin": "*"}],
  ["/api/v1/*.json", {"Content-Type": "application/json; charset=utf-8", "Cache-Control": "public, max-age=3600", "Access-Control-Allow-Origin": "*"}],
  ["/api/v1/docs.md", {"Content-Type": "text/markdown; charset=utf-8", "Cache-Control": "public, max-age=3600", "Access-Control-Allow-Origin": "*"}],
  ["/*.md", {"Content-Type": "text/markdown; charset=utf-8", "Cache-Control": "public, max-age=3600", "Access-Control-Allow-Origin": "*", "Vary": "Accept"}],
  ["/sitemap.xml", {"Content-Type": "application/xml; charset=utf-8", "Cache-Control": "public, max-age=3600"}],
  ["/robots.txt", {"Content-Type": "text/plain; charset=utf-8", "Cache-Control": "public, max-age=3600"}],
];
